copsboot-security:
  mobile-app-client-id: copsboot-mobile-client
  mobile-app-client-secret: ccUyb6vS4S8nxfbKPCrN

spring:
  datasource:
    url: jdbc:postgresql://localhost/copsbootdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: my-postgres-db-pwd
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
  flyway:
    locations: classpath:db/migration/postgresql
